### ISSUE TITLE
Broken: addModule in our forked version

### ISSUE THREAD

**Issue by beniroquai** [AlecVercruysse/uc2-configurator#11]
Hey @AlecVercruysse, 

finally, I got the chance to work on the project again. I had to do many changes on the UC2-Git (branch v3) and the UC2 configurator. It works now for all Applications and also Modules, but the functionality of adding modules with the "add Module" button is somehow broken. I was messing around with the code quite a lot since I'm not really smart enough to program Javascript ;-) .. but at least, I tried.

Before I give up or I say "it's not a bug, it's a feature", I wanted to ask you if you could give me a hint what I could have a look at. 
The current version "live" can be found here: [https://uc2configurator.netlify.app/](https://uc2configurator.netlify.app/) and the forked version is here: [https://github.com/bionanoimaging/uc2-configurator/](https://github.com/bionanoimaging/uc2-configurator/). 

Perhaps you can quickly judge if I can resolve the issue with the `addmodule`function. Thank you so much! 
In any way, the current version is already soo cool!! :)

**Comment by AlecVercruysse** [comment]
Hi, the current version looks beautiful! I'm sure this 

 I'm slightly confused what is the issue since when clicking around it seems to me that the add module button seems to be working.

**Comment by AlecVercruysse** [comment]
I see that bionanoimaging/uc2-configurator@9fcf520 seems to have fixed the issue, so I'll go ahead and close this.

**Comment by beniroquai** [comment]
Yes. Somehow I managed! I guess I learned a lot, but on the way, it felt more like [this](https://www.youtube.com/watch?v=CfsAH9HmQSA&ab_channel=MOHAMADFATHI) ;-) 

It will go live soon. Are you ok with your affiliation/reference? You did most of the part anyway :)

**Comment by AlecVercruysse** [comment]
Absolutely! It certainly looks like you've made some great improvements.
