### ISSUE TITLE
No ZIP if file does not exist

### ISSUE THREAD

**Issue by beniroquai** [AlecVercruysse/uc2-configurator#8]
Next problem ;-) 

Is there a chance to only give an error message if an ```. STL```-file is missing rather than not offering the ZIP file as a download? Where would I do that? I think it's related to an older issue/enhancement.

**Comment by beniroquai** [comment]
The current build can be found [here](https://5fba9fdfc92ebe1a88060861--condescending-mestorf-619480.netlify.app/)

**Comment by AlecVercruysse** [comment]
I think this depends a bit on when the program determines that the zip can't be found.

That would mean either showing an error when the bar is clicked (and it's trying to assemble the zip),
or graying out the bar in the first place and saying that there's an error that doesn't let the user proceed (the two ideas I came up with)

I think the first could be handled in the promise handler of the zipping function (check for 404 errors), which would be easiest. The second might work if you know before you make any requests that there's something missing (like if we see that the config is unfinished) could be handled as a "computed" value in vue. Then the :disabled attribute of the "download" button could be set to evaluate to that.
